spring:
  h2:
    console:
    database: h2
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
